# Generated by Django 6.0.3 on 2026-03-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Bank Account', 'Bank Account')], default='Cash', max_length=50),
        ),
    ]
