# Generated by Django 6.0.3 on 2026-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='vendor_name',
            field=models.CharField(default='General Vendor', max_length=200),
        ),
    ]
