# Generated by Django 6.0.3 on 2026-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_cost_per_unit_item_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=4, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
